using Blater.Frontend.Client.Auto.AutoModels.Types.Form.Timeline;

namespace Blater.Frontend.Client.Auto.AutoInterfaces.Types.Form.Timeline;

public interface IAutoFormTimelineConfigurationBuilder
{
    IAutoFormTimelineMemberConfigurationBuilder AddGroup(AutoFormTimelineGroupConfiguration groupConfiguration);
    IAutoFormTimelineMemberConfigurationBuilder AddGroupCreateOnly(AutoFormTimelineGroupConfiguration groupConfiguration);
    IAutoFormTimelineMemberConfigurationBuilder AddGroupEditOnly(AutoFormTimelineGroupConfiguration groupConfiguration);
    IAutoFormTimelineConfigurationBuilder Actions(AutoFormTimelineActionConfiguration actionConfiguration);
    IAutoFormTimelineConfigurationBuilder ActionsCreateOnly(AutoFormTimelineActionConfiguration actionConfiguration);
    IAutoFormTimelineConfigurationBuilder ActionsEditOnly(AutoFormTimelineActionConfiguration actionConfiguration);
}